version: '3'

services:
  web:
    build: .
    command: python3 Form/manage.py runserver 0.0.0.0:8000 --settings=NucleoGLForm.settings.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"