# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupación / Profesión')),
                ('institution', models.CharField(max_length=100, verbose_name='Institución')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / Celular')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tema')),
                ('requirements', models.CharField(blank=True, max_length=500, null=True, verbose_name='Requerimientos Extras')),
            ],
        ),
    ]
